### ISSUE TITLE
Wyświetlenie listy filmów z wybranej kategorii

### ISSUE THREAD

**Issue by gfilipiak** [GoldenLineHR/MoviesAppPWieladek#1]

**Comment by wielblad** [comment]
@gfilipiak @gkawka domyślam się, że świetnie się bawicie w piątkowy wieczór, ja natomiast rozwiązuje issuesy :) Czy mam gdzieś wystawić wersje online aplikacji z wykonanymi taskami czy wystarczy, że pushne kod? Powoli zbliżam się do końca pierwszego taska.

**Comment by gfilipiak** [comment]
Wystarczy że wrzucisz kodzik i będziemy mogli go odpalić lokalnie :)

--
Gabriel Filipiak

pt., 6.04.2018, 22:52 użytkownik wielblad <notifications@github.com>
napisał:
