### ISSUE TITLE
Powiadamianie moderatora o tym, że doszła opinia do zmoderowania

### ISSUE THREAD

**Issue by gfilipiak** [GoldenLineHR/MoviesAppPWieladek#3]
Po wprowadzeniu przez użytkownika moderator powinien otrzymać email z informacją, że doszła nowa opinia do zmoderowania.

**Comment by wielblad** [comment]
Czy zrobić w bazie tabele użytkowników, którzy są moderatorami czy przyjąć jakiś jeden konkretny email moderatora na który wysyłać wiadomości ?

**Comment by gfilipiak** [comment]
Zdecyduj sam :)

--
Gabriel Filipiak

sob., 7.04.2018, 10:56 użytkownik wielblad <notifications@github.com>
napisał:

**Comment by wielblad** [comment]
na chwilę obecną zrobiłem zwykłą wysyłkę na jeden, wskazany adres. Jak starczy mi czasu to rozbuduję na listę moderatorów z bazy danych, chociaż nie wiem czy sam sobie nie utrudniam, bo później w #4 konsola będzie musiała jakoś rozróżniać moderatorów... czy może nie ma takiej potrzeby ?
